### ISSUE TITLE
Formulaire "Modifier le règlement", prévoir une petite touche "i" d'aide à la saisie

### ISSUE THREAD

**Issue by GT-CNIG-DDU** [IGNF/cnig-sg6-demo#1]
Dans le formulaire "Modifier le règlement", prévoir une petite touche "i" devant le champ "identifiant d'urbanisme" pour indiquer le format attendu.
J'ai saisi : `<insee>_<typedoc>_<datappro>` en supposant que c'était cela.

![2022-11-08_105931](https://user-images.githubusercontent.com/79853274/200535186-2c6ca5c9-c997-4913-901f-d0fbbfd94e88.png)

**Comment by MFrangi** [comment]
Nous ne ferons pas d'aide contextuelle pour l'instant mais une aide sera apporté à l'utilisateur avec des placeholders (voir issue #25).
