### ISSUE TITLE
Les modifications d'intitulés dans le sommaire ne sont pas prises en compte

### ISSUE THREAD

**Issue by GT-CNIG-DDU** [IGNF/cnig-sg6-demo#10]
Les modifications d'intitulés dans le sommaire ne sont pas prises en compte :
J'ai intitulé mon titre : "Occupations et utilisations du sol interdites"
Je souhaite le renommer "Ua -  Occupations et utilisations du sol interdites" (en faisant modifier puis "mettre à jour")
dès que je-clique sur le titre dans le sommaire, li redevient "Occupations et utilisations du sol interdites"

Donc je ne peux pas le modifier, en dehors de le supprimer et le re-créer totalement :-(

**Comment by GT-CNIG-DDU** [comment]
Je complète le commentaire précédent : 
- la modification est prise en compte si elle est effectuée dans le panneau d'édition
- elle n'est pas prise en compte (cf. commentaire ci-dessus) en utilisant la touche  "modifier" dans le panneau de gauche "sommaire"

**Comment by MFrangi** [comment]
Traité
