### ISSUE TITLE
Erreur à l'import

### ISSUE THREAD

**Issue by GT-CNIG-DDU** [IGNF/cnig-sg6-demo#12]
Je n'ai pas pu "charger " le xml ci-joint, exporté (sans erreur cette fois) depuis l'outil d'édition
[export_44003_reglement_20200224.zip](https://github.com/IGNF/cnig-sg6-demo/files/10374927/export_44003_reglement_20200224.zip)

**Comment by MFrangi** [comment]
A priori, traité dans l'issue #7
