### ISSUE TITLE
Prévoir la possibilité de réordonner les titres dans le sommaire

### ISSUE THREAD

**Issue by GT-CNIG-DDU** [IGNF/cnig-sg6-demo#13]
Dans cet exemple, l' "Article 1 – Champs d’application", rédigé après coup, se rattache au "titre i : dispositions generales"
Il n'est actuellement pas possible de "remonter" le titre "Article 1 – Champs d’application" en deuxième place dans le sommaire
![2023-01-10_101914](https://user-images.githubusercontent.com/79853274/211511590-4972c068-6391-47ff-80c8-e718b5bf10e0.png)

**Comment by MFrangi** [comment]
Ne sera pas traité dans l'immédiat. À voir si on le fait dans le futur.

**Comment by MFrangi** [comment]
Je vais modifier l'outil pour pouvoir insérer un titre n'importe où et pas seulement ajouter un titre à la suite de tous les autres.

Je vais aussi essayer de proposer quelque chose pour rendre plus claire l'imbrication des titres.

**Comment by GT-CNIG-DDU** [comment]
La touche `+` permet d'insérer un titre au dessus d'un autre, c'est très bien. _(à intégrer dans le manuel opérateur...)_
Mais comment déplacer un titre (cf. la demande initiale), faut-il le supprimer et ensuite le recréer à l'endroit voulu ?

**Comment by MFrangi** [comment]
Oui, pour l'instant pas d'autre manière. Réordonner les titres, c'est un peu plus dur à faire et ça va charger l'interface avec des nouveaux boutons. 
Je me suis dit que le besoin de déplacer un titre existant devait être assez rare mais peut être que je me trompe. Si c'est la cas, je développerai la fonctionnalité.
