### ISSUE TITLE
Le remplissage des formulaires de titres disparait à l'export / import du règlement

### ISSUE THREAD

**Issue by GT-CNIG-DDU** [IGNF/cnig-sg6-demo#14]
J'ai rempli le premier titre "titre i : dispositions generales"
![2023-01-10_100808](https://user-images.githubusercontent.com/79853274/211512771-488bc4af-be0f-4f90-be6e-7083b21a39eb.png)

Mais après la séquence : export / nouveau / import il se retrouve vide : 
=> Contrairement aux autres titres qui conservent leur remplissage
![2023-01-10_100931](https://user-images.githubusercontent.com/79853274/211513035-ec799297-7028-48ba-9457-2c524998b396.png)

**Comment by GT-CNIG-DDU** [comment]
Je rectifie ce point :
Après manipulations normales (sauvegarde / export et réimport) et sans erreur ni plantage, j'ai finalement perdu le remplissage de **tous** mes formulaires de titre

**Comment by MFrangi** [comment]
Traité
