### ISSUE TITLE
Sommaire et affichage des titres

### ISSUE THREAD

**Issue by alisonlenain** [IGNF/cnig-sg6-demo#19]
Changer le terme "Numéro" par "Niveau" dans la section "Modifier le Titre" et corriger la perte des modifications d'intitulés  cf issue #10.
Faire apparaitre également les différents niveaux de titres dans le sommaire.

**Comment by MFrangi** [comment]
Le niveau de titre a été ajouté dans le formulaire. Par contre, j'ai laissé le champ "numéro" car il est présent dans le modèle UML.
