### ISSUE TITLE
A quoi correspond "Référence interne"

### ISSUE THREAD

**Issue by GT-CNIG-DDU** [IGNF/cnig-sg6-demo#2]
1/ A quoi correspond `Référence interne` ? Est-ce "Niveau de titre dans la hiérarchie" qui n'apparaît pas dans le formulaire ?
2/ Ici aussi, mettre des info-bulles, notamment pour indiquer de saisir `porteeGenerale`
3/ une coquille : ect. => etc

![2022-11-08_111049](https://user-images.githubusercontent.com/79853274/200537177-5646c2a3-4311-4ed8-bcb9-e8dc7c5de8b5.png)

**Comment by GT-CNIG-DDU** [comment]
Le lien entre les champs du standard "niveau" et "numero" ne sont pas clairs avec ce que présente l'interface "Numéro" et "Référence interne".
Une aide contextuelle est indispensable.

**Comment by MFrangi** [comment]
Une aide sera apportée à l'utilisateur avec des placeholders (voir issue #25). Le champ niveau de titre à été ajouté (issue #19).

**Comment by GT-CNIG-DDU** [comment]
Ok, et le manuel utilisateur expliquera bien la différence.

**Comment by AntoineMoriceau** [comment]
J'ai aussi considéré que la différence entre numéro et référence interne n'était pas claire. 
Mon interprétation :
Numéro > forcément un chiffre incrémental
Référence interne > tel que ça apparait à l'écrit (ex "Titre IV" ou "Paragraphe 1").
Ca demande à être éclairci mais peut être que le guide utilisateur est le lieu pour

**Comment by alisonlenain** [comment]
A traiter lors de la prochaine réunion. J'avais indiqué dans le manuel utilisateur que "la référence interne fait référence aux numéros des articles concernés dans le règlement littéral"

**Comment by MFrangi** [comment]
Dans le modèle UML, je n'ai pas l'impression qu'il y ait de champ "référence interne", est-ce que c'est celui-là qu'il faut enlever ?

**Comment by alisonlenain** [comment]
Complétement d'accord avec vos remarques

**Comment by MFrangi** [comment]
Par contre, niveau et numéro sont des champs de type "nombre", on ne peut pas mettre de placeholder.

**Comment by MFrangi** [comment]
Je peux faire des petits "i" mais c'est un peu étrange d'en avoir ici et à aucun autre endroit de l'application.
Je peux aussi marquer "Niveau du titre dans la hiérarchie (Ex : 1, 2, 3, etc.)" au lieu de simplement "Niveau".

Sinon, je me rends compte que dans le code, le "référence interne" correspond au "href" du modèle UML. C'est censé être quoi ce "href" ? Est-ce qu'on l'ignore et on enlève quand même le champ "référence interne" ?

**Comment by alisonlenain** [comment]
• l’attribut href pour définir la source d’un lien hypertexte :
		<a href="http://monReglement.xml">

**Comment by alisonlenain** [comment]
On peut faire un renvoi vers le manuel opérateur au lieu des points d'informations. 
Je ferai la mise à jour du manuel opérateur d'ici la prochaine réunion

**Comment by MFrangi** [comment]
Du coup, ça n'a rien à voir avec l'attribut "numéro". C'est juste un moyen de mettre un lien hypertexte sur le titre. Donc est-ce qu'on garde ce champ (sachant qu'on peut très bien faire un lien hypertexte directement dans l'éditeur de texte) ?

**Comment by alisonlenain** [comment]
Je pense qu'on peut supprimer ce champ sauf si quelqu'un s'y oppose

**Comment by GT-CNIG-DDU** [comment]
Je suis d'accord pour le supprimer de la classe `Titre`.
Il reste pertinent au niveau de la classe `ReglementPLU`, mais pour cette classe c'est l'attribut `lien` qui tient le rôle.

**Comment by GT-CNIG-DDU** [comment]
PS : Cela implique de le supprimer du [schema UML du standard (page 13)](http://cnig.gouv.fr/IMG/pdf/230112_standard_cnig_sru_v2022-10.pdf#page=13) et du XSD correspondant.

**Comment by alisonlenain** [comment]
Le nouveau schéma UML et le schéma XSD ont été modifiés et déposés ici : https://github.com/cnigfr/structuration-reglement-urbanisme/tree/master/schemas
