### ISSUE TITLE
Afficher plutôt : "Consulter le règlement sur le Géoportail de l'urbanisme"

### ISSUE THREAD

**Issue by GT-CNIG-DDU** [IGNF/cnig-sg6-demo#20]
Une fois renseignée, la rubrique "PLU de XXX" affiche la mention "Consulter la fiche document sur le Géoportail de l'urbanisme"
à remplacer par "Consulter le règlement sur le Géoportail de l'urbanisme"

**Comment by MFrangi** [comment]
Sera traité dans l'issue #23
