### ISSUE TITLE
Code SIREN pour les PLUi

### ISSUE THREAD

**Issue by alisonlenain** [IGNF/cnig-sg6-demo#21]
Dans le cadre de la saisie des communes pour le cas d'un PLUi il serait plus pertinent de ne saisir que le code SIREN de la collectivité avec son sous-code lettre à la place de la liste des codes INSEE des communes impactées.
La liste des communes impactée reste toutefois pertinente.

[nkulpinski](https://github.com/nkulpinski)

**Comment by MFrangi** [comment]
Quel doit-être l'intitulé exact du champ ? "Code SIREN de la collectivité" ?

**Comment by GT-CNIG-DDU** [comment]
Le [standard CNIG PLU](http://cnig.gouv.fr/IMG/pdf/230112_standard_cnig_plu_v2022-10.pdf) le définit comme le _numéro SIREN de l'intercommunalité autorité compétente du document d'urbanisme_
Tu peux utiliser la forme courte : _Code SIREN de l'intercommunalité_
_Code SIREN de la collectivité_ convient aussi.

**Comment by alisonlenain** [comment]
Sera résolue avec #32 issue
