### ISSUE TITLE
Affectation du niveau de titre : lien entre l'éditeur texte et les attributs

### ISSUE THREAD

**Issue by GT-CNIG-DDU** [IGNF/cnig-sg6-demo#3]
Si je comprends bien (?) `Numéro` (qui est un entier incrémentable, cf. copie d'écran) doit correspondre au `Niveau de titre` du standard SRU

1/ Si cette hypothèse est exacte : renommer `Numéro` en `Niveau de titre`
2/ Ayant déjà défini mon niveau de titre lors de l'édition du paragraphe (ici : niveau 3), faire en sorte que le champ de saisie contienne déjà la valeur `3`, donc sans avoir à la re-saisir.
3/ Et inversement : si je saisis `4` ce titre passera en niveau 4

![2022-11-08_113758](https://user-images.githubusercontent.com/79853274/200544169-7c570dd6-c620-4745-b8ff-eb6e442f0be4.png)

**Comment by MFrangi** [comment]
Traité dans l'issue #19
