### ISSUE TITLE
Aide contextuelle 01

### ISSUE THREAD

**Issue by GT-CNIG-DDU** [IGNF/cnig-sg6-demo#31]
L'aide contextuelle indiquée dans le champ "Lien, ressource web ou GPU" ne convient pas

![image](https://user-images.githubusercontent.com/79853274/226884129-02188009-a29f-41ea-9cc0-0e97b1d548c8.png)

**Comment by alisonlenain** [comment]
Oui, il faudrait plutôt mettre : https://wxs-gpu.mongeoportail.ign.fr/externe/documents/DU_44003/b5a41ee6f67e46ff2bdda06b2b51caf6/44003_reglement_20200224.pdf

**Comment by AntoineMoriceau** [comment]
Je confirme que je suis tombé dans le panneau lors de mon test (j'ai mis le lien de téléchargement du ZIP du CNIG complet). Le titre du champ au sein du panneau pourrait être "Lien vers l'URL du règlement écrit au sein du GPU" comme le suggère Arnauld (sous entendu dans le manuel oui mais aussi dans le front de l'outil)

**Comment by GT-CNIG-DDU** [comment]
Encore mieux : suivant une information récemment fournie par le projet GPU, il existe un URL normalisé vers le règlement du document d'urbanisme : https://www.geoportail-urbanisme.gouv.fr/api/document/download-by-partition/DU_<INSEE/SIREN>/file/<INSEE/SIREN>_reglement_<DATAPPRO>

Le champ de saisie apparaît inutile à remplir dès lors que l'on dispose de l'identifiant du document d'urbanisme, qui contient INSEE ou SIREN et DATAPPRO, (et évidemment... que le document d'urbanisme est publié sur le GPU).

**Comment by GT-CNIG-DDU** [comment]
Des caractères ne sont pas passés dans mon précédents post. Il faut lire  :  

https://www.geoportail-urbanisme.gouv.fr/api/document/download-by-partition/DU_<INSEE/SIREN>/file/<INSEE/SIREN>\_reglement_\<DATAPPRO>.pdf

Exemple : 
https://www.geoportail-urbanisme.gouv.fr/api/document/download-by-partition/DU_29044/file/29044_reglement_20230307.pdf
