### ISSUE TITLE
Interface utilisateur 05 et Manuel utilisateur

### ISSUE THREAD

**Issue by GT-CNIG-DDU** [IGNF/cnig-sg6-demo#33]
Remplacer : `Zone (U, Ua, ect.)`
par : `Zone (ex : U, Ua, etc.) ou la mention porteeGenerale si toutes les zones sont concernées`
![2023-03-27_141214](https://user-images.githubusercontent.com/79853274/227941043-9abc1695-0694-4329-b77c-2ac009989e22.png)

Modifier le manuel opérateur (page 6) en remplaçant DISPOSITIONS GENERALES par porteeGenerale : 
![2023-03-27_142747](https://user-images.githubusercontent.com/79853274/227941554-a9aa0eb7-7498-400b-a7ef-78339f90617c.png)

**Comment by GT-CNIG-DDU** [comment]
Réouverture de l'issue afin de s'assurer que le manuel opérateur a été actualisé page 6

**Comment by alisonlenain** [comment]
Il a été actualisé. Il sera envoyé au SG6 ce soir
