### ISSUE TITLE
Perte d'informations au réimport de <insee>_reglement_<datappro>.xml

### ISSUE THREAD

**Issue by GT-CNIG-DDU** [IGNF/cnig-sg6-demo#37]
J'ai exporté mon édition du PLU de Ancenis : 

Sommaire "plié" : 
![2023-03-27_151332](https://user-images.githubusercontent.com/79853274/227952057-e3f620b4-f7d2-4a79-9fc4-16c47056deb1.png)

Sommaire "déplié" : 
![2023-03-27_145744](https://user-images.githubusercontent.com/79853274/227951698-32e25b55-c6a1-4441-80e0-83f7668eeb08.png)

En réimportant directement le XML exporté, j'obtiens ceci :   
 
![2023-03-27_153227](https://user-images.githubusercontent.com/79853274/227952994-90352dc6-2501-44c9-81d4-b27180687a2a.png)

C'est à dire que j'ai perdu tous les sous-titres et leurs contenus.

Pourtant ils semblent bien avoir été exportés dans le fichier `export_44003_reglement_20200224.xml` ci-joint : 
[export_44003_reglement_20200224.zip](https://github.com/IGNF/cnig-sg6-demo/files/11079204/export_44003_reglement_20200224.zip)

L'import de ce xml a été testé sous Firefox, Chrome et Edge, avec le même résultat.

**Comment by AntoineMoriceau** [comment]
J'observe la même chose après export puis import. Seul le titre 1 apparait en front et tout le reste (les sous titres et le texte) est invisible. Tout est bien dans le XML néanmoins :
[https://share.sogefi-web.com/download.php?file=export_16243_reglement_20200130.xml](url)

**Comment by GT-CNIG-DDU** [comment]
Bug résolu le 31/03/23 : le document importé est identique à celui exporté
_testé sur le même lot de données DU Ancenis comprenant un titre principal et une arborescence à trois niveaux_ : [export_44003_reglement_20200224.zip](https://github.com/IGNF/cnig-sg6-demo/files/11135517/export_44003_reglement_20200224.zip)

**Comment by AntoineMoriceau** [comment]
Test de réimport OK ce jour
