### ISSUE TITLE
Impossible de supprimer un titre

### ISSUE THREAD

**Issue by AntoineMoriceau** [IGNF/cnig-sg6-demo#38]
quand j'essaie de supprimer un titre, il n'est pas vraiment supprimé il réapparaît (en fin de liste). Sans doute parce que j'y ai associé des titres d'un niveau inférieur et du texte à l'intérieur. 
Je suppose que techniquement la suppression d'un titre qui a du contenu de niveau inférieur est bridée (et c'est logique) d'où le besoin de clarifier en front cette logique d'imbrication car ce n'est pas visible/lisible (cf #13)

**Comment by MFrangi** [comment]
En fait la suppression n'est pas bridée, c'est juste un bug qui apparait dans certains cas. Mais ça pose une vraie question : lorsqu'on supprime un titre, est-ce que l'on doit supprimer tous les titres de niveau inférieur ? Ça semblerait plutôt logique de le faire (avec un message d'alerte préalable pour informer l'utilisateur).

**Comment by AntoineMoriceau** [comment]
C'est à discuter parce que ce n'est pas neutre comme choix. En tout cas, ça implique de modéliser (et d'afficher en front) la logique d'imbrication des niveaux

**Comment by alisonlenain** [comment]
Ajouter un message d’alerte avant la suppression du titre de niveau 1 et rattacher les titres de niveaux inférieurs à un autre titre de niveau 1 ou créer un nouveau titre de niveau 1 pour les associer.  .
