### ISSUE TITLE
Empêcher de modifier le titre dans la zone de droite

### ISSUE THREAD

**Issue by AntoineMoriceau** [IGNF/cnig-sg6-demo#39]
Il me parait utile d'empêcher la modification du titre dans la zone de droite dédiée à la modification du paragraphe (une vision figée qui réécrit le titre tel qu'il vient du sommaire mais qui ne soit pas modifiable).
Il est important de saisir les titre dans la zone sommaire (et uniquement là) pour ne pas créer de confusion

**Comment by alisonlenain** [comment]
Sera abordée lors de la prochaine réunion

**Comment by GT-CNIG-DDU** [comment]
Je soutiens la proposition de @AntoineMoriceau d'empêcher la modification du titre dans la zone de droite dédiée à la modification du paragraphe.
