### ISSUE TITLE
L'ascenseur "remonte" au début quand on essaie de modifier un titre qui se trouve plus bas

### ISSUE THREAD

**Issue by AntoineMoriceau** [IGNF/cnig-sg6-demo#40]
La modification d'un titre loin dans la liste ("ascenseur baissé") remonte la liste (ascenseur au début) et on ne voit plus le titre qu'on tente de modifier

**Comment by GT-CNIG-DDU** [comment]
Je confirme. J'ai rencontré le même bug.
