### ISSUE TITLE
Référencer le manuel opérateur dans l'interface

### ISSUE THREAD

**Issue by MFrangi** [IGNF/cnig-sg6-demo#43]
Mettre un lien vers le manuel opérateur dans l'interface.

**Comment by alisonlenain** [comment]
Mettre à jour suite aux nouvelles fonctionnalités ajoutées si elles sont validées lors de la réunion du 05/09.

**Comment by alisonlenain** [comment]
MAJ du manuel à faire + référencement dans interface
