### ISSUE TITLE
Un sous-titre hérite par défaut de la Zone du titre parent

### ISSUE THREAD

**Issue by GT-CNIG-DDU** [IGNF/cnig-sg6-demo#5]
Faire hériter par défaut un sous-titre de la `Zone` du titre parent, également du `Code INSEE` (sauf résolution de #4)

**Comment by alisonlenain** [comment]
A valider avec les membres du SG6

**Comment by GT-CNIG-DDU** [comment]
C'est dans le standard SRU de niveau 1

**Comment by MFrangi** [comment]
Pour être sûr d'avoir bien compris : un titre de niveau 2 ou plus a strictement toujours la même zone que le titre de niveau 1 dont il découle ?

**Comment by GT-CNIG-DDU** [comment]
Oui, par construction du règlement d'urbanisme.
La zone pouvant être : 
- une zone bien identifiée, par son idzone. Exemple : `Uh`
- toutes les zones, en utilisant dans ce cas la valeur conventionnelle `porteeGenerale`

**Comment by MFrangi** [comment]
D'accord. Donc on ne demandera à l'utilisateur de renseigner la zone que si il s'agit d'un titre de niveau 1. Pour les autres, ce sera directement hérité du titre parent.
