### ISSUE TITLE
Insérer une image déposée sur un drive

### ISSUE THREAD

**Issue by GT-CNIG-DDU** [IGNF/cnig-sg6-demo#6]
Cette [image déposée sur un drive](https://drive.google.com/file/d/1OgTLDKuADUOfnBaPFP8kglahiByOyDtN/view?usp=share_link) n'apparait pas. Comment la faire apparaître ?

![2022-11-08_140005](https://user-images.githubusercontent.com/79853274/200571231-a17cb0b3-4ba4-464c-bed2-2fa0d4f62ae5.png)

**Comment by mborne** [comment]
Regardé rapidement, mais pas sûr que le drive soit prévu pour fournir des liens intégrables dans un site web (je ne trouve pas un tel lien sur la page "view" en question).

**Comment by MFrangi** [comment]
Il semblerait que pour une image depuis un drive google, il faille mettre un lien avec le format suivant :
 https://drive.google.com/uc?export=view&id=[identifiant de l'image]

Dans le cas présent, il faut donc mettre l'url suivant : 
https://drive.google.com/uc?export=view&id=1OgTLDKuADUOfnBaPFP8kglahiByOyDtN

**Comment by GT-CNIG-DDU** [comment]
Merci @MFrangi , nous testerons cela, mais pourras-tu nous indiquer lorsque les autres issues seront résolues, afin que nous puissions retester globalement l'outil, si possible avant la prochaine réunion du SG6 du 10 février après-midi ?

**Comment by alisonlenain** [comment]
Bonjour Arnauld, 

Nous avons prévu de faire un point ensemble sur l'outil demain matin Manuel et moi. 
J'enverrai un message à l'ensemble des membres du SG6 pour prévenir lorsque l'outil sera opérationnel.

**Comment by MFrangi** [comment]
Traité. Information à mettre dans le manuel utilisateur.
