### ISSUE TITLE
Impossibilité de recharger le règlement que je viens d'exporter !

### ISSUE THREAD

**Issue by GT-CNIG-DDU** [IGNF/cnig-sg6-demo#7]
Impossibilité de recharger [le règlement que je viens d'exporter en xml](https://drive.google.com/file/d/1WRGux6xRY41uE-wXy6AOF8Q4z2qlxU7S/view?usp=share_link) !
Test avec trois navigateurs :
- Le règlement ne se charge pas sous Firefox
- Edge n'ouvre pas la page https://cboucheign.github.io/sg6-demo/examples/
- Seules les deux premières lignes du règlement se chargent sous Chrome : 

![2022-11-08_140917](https://user-images.githubusercontent.com/79853274/200573359-fd230903-2303-4a20-b6a6-b3e27193099e.png)

**Comment by mborne** [comment]
Bonjour,

J'ai jeté un oeil à ce problème : 

* Le parser XML du navigateur (DOMParser) est sensible aux `<br>` (et activer la tolérance HTML pose d'autres problèmes...)
* Même en corrigeant le `<br>` => `<br />`, il reste un problème de chargement

=> J'ai mis en place un cadre pour automatiser des tests sur ce point. Je suggère d'industrialiser à minima le démonstrateur sur ce point en : 

* [ ] Renforçant les tests automatisés
* [ ] Basculant sur l'utilisation de la bibliothèque `xmldom` pour la lecture du XML (évitera des surprises sur ce point avec les navigateurs)

Mickaël

PS : Pour une véritable industrialisation, je pense que nous ne couperons à passer en mode projet ne serait-ce que pour avoir la possibilité d'héberger quelques services en backend (ex : validation du XML en fonction du schéma XSD, stockage d'image pour éviter l'utilisation de service externes incompatibles (c.f. #6 ) ,...

**Comment by MFrangi** [comment]
Bonjour,

Un des problèmes était la gestion des identifiants lors de l'export. 

Dans le fichier en question, on peut voir que certains éléments ont le même identifiant, certains titres ont des "idContenu" et certains contenus ont des "idTitre".

Ce problème est normalement réglé dans la nouvelle version en ligne actuellement. Par contre, il faut recréer le fichier depuis le début. Le fichier précédemment exporté est "corrompu" à cause des mauvais identifiants.

**Comment by MFrangi** [comment]
Traité.
